version: '3.4'

services:
  backend.api:
    image: ${DOCKER_REGISTRY-}backendapi
    depends_on:
    - sqldata
    build:
      context: .
      dockerfile: src/Backend.API/Dockerfile
    environment:
      DBConnection: "Data Source=sqldata,1433;Initial Catalog=master;Persist Security Info=True;User ID=sa;Password=Stefanini@123"
    ports:
     - "6504:80"


  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Stefanini@123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
