version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    environment:
      - ELASTIC_PASSWORD=senhaelastic
      - KIBANA_PASSWORD=senhakibana
      - STACK_VERSION=8.3.1
      - discovery.type=single-node
      - LICENSE=basic
      - KIBANA_PORT=5601
      - ES_PORT=9200
      - MEM_LIMIT=262144
    ports:
      - "5611:5601"
      - "9200:9200"

  seq:
    image: datalust/seq:latest
    environment:
        - ACCEPT_EULA=Y
        - $HOST_PATH_TO_SEQ:/data
        - $HOST_HTTP_PORT:9240
        - $HOST_INGESTION_PORT:5341
        - HOST_PATH_TO_SEQ:/data
        - HOST_HTTP_PORT:9240
        - HOST_INGESTION_PORT:5341
    ports:
      - "9540:5341"
      - "9240:9240"